import{S as w,a as q,i as s}from"./assets/vendor-DWXSRYDZ.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function i(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(t){if(t.ep)return;t.ep=!0;const o=i(t);fetch(t.href,o)}})();const m=document.querySelector(".gallery"),$=new w(".gallery a"),f=document.querySelector(".loader"),h=document.querySelector(".js-load-more");function g(r){const e=r.map(({webformatURL:i,largeImageURL:l,tags:t,likes:o,views:n,comments:S,downloads:v})=>`
        <li class="gallery-item">
        <a href="${l}">
        <img src="${i}" alt="${t}" title="${t}"/>
        <div class="info">
<p><b>💖 likes </b>${o} </p>
<p><b>👁️ views </b> ${n}</p>
<p><b>💬 comments </b>${S} </p>
<p><b>⬇️ downloads </b>${v} </p>
        </div>
        </a>
        </li>`).join("");console.log(e),m.insertAdjacentHTML("beforeend",e),$.refresh()}function M(){m.innerHTML=""}function p(){f.classList.add("is-visible")}function y(){f.classList.remove("is-visible")}function b(){h.classList.add("load-more-hiden")}function u(){h.classList.remove("load-more-hiden")}async function L(r,e=1){const{data:i}=await q.get("https://pixabay.com/api/",{params:{page:e,per_page:15,key:"50835299-cfd675820214f48c95352b76b",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0}});return i}const R=document.querySelector(".form"),E=document.querySelector('[name="search-text"]');document.querySelector(".gallery");document.querySelector(".loader");const O=document.querySelector(".js-load-more");let d=1,c="",a=0;R.addEventListener("submit",P);O.addEventListener("click",x);function P(r){if(r.preventDefault(),c=E.value.trim().toLowerCase(),d=1,a=0,!c){s.error({title:"Error",message:"Please enter a search term.",position:"topRight"});return}M(),u(),p(),L(c,d).then(e=>{if(e.hits.length===0){s.error({title:"",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(e.hits),a+=e.hits.length,a>=e.totalHits?(u(),s.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):b()}).catch(e=>{s.error({title:"Error",message:`Something went wrong: ${e.message}`,position:"topRight"})}).finally(()=>{y()})}async function x(){d+=1,u(),p();try{const r=await L(c,d);g(r.hits);const e=document.querySelector(".gallery-item");if(e){const{height:i}=e.getBoundingClientRect();window.scrollBy({top:i*2,behavior:"smooth"})}a+=r.hits.length,a>=r.totalHits?(u(),s.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):b()}catch(r){s.error({title:"Error",message:`Something went wrong: ${r.message}`,position:"topRight"})}finally{y()}}
//# sourceMappingURL=index.js.map
